### ISSUE TITLE
[BUG] log message incorrectly showing hosting node name

### ISSUE THREAD

**Issue by venkataanil** [cloud-bulldozer/k8s-netperf#111]
**Describe the bug**
client-across and server pod ip addresses are incorrect in the log message -
time="2023-10-10 06:20:52" level=debug msg="server Running on ip-10-0-75-22.us-west-2.compute.internal with IP **10.0.75.22**"                                                  
time="2023-10-10 06:20:52" level=debug msg="client-across Running on ip-10-0-88-122.us-west-2.compute.internal with IP **10.0.88.122**"                                         
time="2023-10-10 06:20:53" level=debug msg="Executing workloads. hostNetwork is false, service is false"                                                                    
time="2023-10-10 06:20:53" level=debug msg="🔥 Client (client-across-7f5f95b667-bxdq7,10.153.0.13) starting netperf against server : 10.139.0.17"                           
time="2023-10-10 06:20:53" level=info msg="🗒️  Running netperf TCP_RR (service false) for 60s "                                                                              
time="2023-10-10 06:20:53" level=debug msg="[bash super-netperf 1 -H 10.139.0.17 -l 60 -t TCP_RR -- -k rt_latency,p99_latency,throughput,throughput_units,remote_recv_calls,local_send_calls,local_transport_retrans -m 1024 -R 1]"

`[root@vkommadi network-perf-v2]# oc get pods -o wide
NAME                             READY   STATUS    RESTARTS   AGE     IP            NODE                                        NOMINATED NODE   READINESS GATES
client-across-7f5f95b667-bxdq7   1/1     Running   0          5m33s   10.153.0.13   ip-10-0-88-122.us-west-2.compute.internal   <none>           <none>
server-fb46448d8-hl4wp           1/1     Running   0          5m30s   10.139.0.17   ip-10-0-75-22.us-west-2.compute.internal    <none>           <none>
[root@vkommadi network-perf-v2]# `

Log should show client-across ip as 10.153.0.13 instead of 10.0.88.122 and server ip as 10.139.0.17 instead of 10.0.0.75

**To Reproduce**
1. run pod2pod secenario

**Expected behavior**
For example log message should have been like this
time="2023-10-10 06:20:52" level=debug msg="server Running on ip-10-0-75-22.us-west-2.compute.internal with IP **10.139.0.17**"                                                  
time="2023-10-10 06:20:52" level=debug msg="client-across Running on ip-10-0-88-122.us-west-2.compute.internal with IP **10.153.0.13**"

**Comment by jtaleric** [comment]
Can you confirm you are running with `tag: v0.1.15` ?

Also, the expected output is correct. 

`DEBU[2023-10-10 08:16:34] client-across Running on perf-fc640-6.perf.lab.eng.rdu2.redhat.com with IP **10.1.184.209** ` 

Which we see can look at the `oc get nodes -o wide`

`perf-fc640-6.perf.lab.eng.rdu2.redhat.com   Ready    worker   714d     v1.21.11+6b3cbdd   **10.1.184.209**   <none>        Red Hat Enterprise Linux CoreOS 48.84.202206281246-0 (Ootpa)   4.18.0-305.49.1.el8_4.x86_64   cri-o://1.21.8-6.rhaos4.8.gitd78036c.el8`

Before launching the pods, we do not have the IP address, as it hasn't been allocated or annotated to the pod. I am just calling out the Host the pod was scheduled to, and the IP of that Host -- not the pod.

**Comment by venkataanil** [comment]
We misunderstood that it is printing the pod IP. Thanks for the explanation.
