### ISSUE TITLE
[RFE] Create namespaces

### ISSUE THREAD

**Issue by rsevilla87** [cloud-bulldozer/k8s-netperf#119]
**Is your feature request related to a problem? Please describe.**

k8s-netperf should take care of creating/removing the required namespaces so we don't need to create it externally.

**Comment by jtaleric** [comment]
I have gone back and forth on this... There was once a pattern in k8s where tools would explicitly expect the user to create the namespace/service accounts to avoid someone doing something dumb in production...  I don't have a strong feeling one way or another.
