### ISSUE TITLE
[BUG] uperf incorrectly reporting RR op/s

### ISSUE THREAD

**Issue by venkataanil** [cloud-bulldozer/k8s-netperf#144]
**Describe the bug**
uperf output has both "throughput in Mbps" and "Average ops". We are mistakenly reporting "throughput Mbps" as  "op/s". For example, in my run "267.433574 Mbps" is reported as "267.433574 (OP/s) "

DEBU[2024-06-05 14:15:28] Storing uperf sample throughput: 267.433574 Mbps, P99 Latency 33.969550, Average ops: 32645.700000 

DEBU[2024-06-05 14:15:29] Rendering RR Transaction results             
+---------------+---------+----------+-------------+--------------+---------+--------------+-----------+----------+---------+---------------------+--------------------------+
|  RESULT TYPE  | DRIVER  | SCENARIO | PARALLELISM | HOST NETWORK | SERVICE | MESSAGE SIZE | SAME NODE | DURATION | SAMPLES |      AVG VALUE      | 95% CONFIDENCE INTERVAL  |
+---------------+---------+----------+-------------+--------------+---------+--------------+-----------+----------+---------+---------------------+--------------------------+
| 📊 Rr Results | netperf | TCP_RR   | 1           | true         | false   | 1024         | false     | 10       | 1       | 25986.000000 (OP/s) | 0.000000-0.000000 (OP/s) |
| 📊 Rr Results | uperf   | TCP_RR   | 1           | true         | false   | 1024         | false     | 10       | 1       | 267.433574 (OP/s)   | 0.000000-0.000000 (OP/s) |

**Comment by jtaleric** [comment]
Yikes - are you putting together a patch for this @venkataanil ?
