### ISSUE TITLE
[BUG] k8snetperf fails to start with the latest release

### ISSUE THREAD

**Issue by SachinNinganure** [cloud-bulldozer/k8s-netperf#147]
Describe the bug
I started the test on the terminal and hit the below issue.
[sninganu@sninganu ~]$ git clone https://github.com/cloud-bulldozer/k8s-netperf.git
Cloning into 'k8s-netperf'...
remote: Enumerating objects: 5765, done.
remote: Counting objects: 100% (464/464), done.
remote: Compressing objects: 100% (188/188), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
error: 7102 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

the last commit seen is https://github.com/cloud-bulldozer/k8s-netperf/commit/ede99db2506f3afbe930e3906904542cdc217e90

**Comment by krishvoor** [comment]
Hi, @SachinNinganure It sounds like a flaky issue, can you perhaps retry? 
```
git clone https://github.com/cloud-bulldozer/k8s-netperf.git
Cloning into 'k8s-netperf'...
remote: Enumerating objects: 5765, done.
remote: Counting objects: 100% (468/468), done.
remote: Compressing objects: 100% (190/190), done.
remote: Total 5765 (delta 290), reused 335 (delta 220), pack-reused 5297
Receiving objects: 100% (5765/5765), 6.74 MiB | 5.24 MiB/s, done.
Resolving deltas: 100% (3114/3114), done.
```

Unless you are taking advantage of the recent changes in main branch, will encourage you to download the binaries from
https://github.com/cloud-bulldozer/k8s-netperf/releases

**Comment by SachinNinganure** [comment]
doesn't help. some other issue with 22
bash: ./bin/amd64/k8s-netperf: No such file or directory

**Comment by SachinNinganure** [comment]
Sorry... I missed to mention that
The cluster I am trying to run this is Hybrid
4 rhel8.10 and 10 rhcos nodes

**Comment by jtaleric** [comment]
> Sorry... I missed to mention that The cluster I am trying to run this is Hybrid 4 rhel8.10 and 10 rhcos nodes

That is a key... Can I get access to this cluster?

**Comment by jtaleric** [comment]
@SachinNinganure can I get an update here?

**Comment by SachinNinganure** [comment]
I had run few tests @jtaleric  looks good 
thank you

**Comment by jtaleric** [comment]
ack - @SachinNinganure can you close this out of we are good?
