### ISSUE TITLE
[RFE] Explicit across AZ testing

### ISSUE THREAD

**Issue by jtaleric** [cloud-bulldozer/k8s-netperf#80]
**Describe the solution you'd like**
Currently k8s-netperf will attempt to place client/server on nodes in the same AZ assuming the zone has enough nodes. We should allow the user to explicitly state if they want the client/server to be across az, similar to how we have `--local` option.

**Comment by SachinNinganure** [comment]
multi_az was set to true by default in uperf runs; https://github.com/cloud-bulldozer/e2e-benchmarking/blob/master/workloads/network-perf/env.sh#LL16C14-L16C14

I was thinking of this sometime ago. this is good to be enhanced. TY
